/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var transaction_info_pb = require('./transaction_info_pb.js');
goog.object.extend(proto, transaction_info_pb);
goog.exportSymbol('proto.types.AccountStateProof', null, global);
goog.exportSymbol('proto.types.AccumulatorProof', null, global);
goog.exportSymbol('proto.types.EventProof', null, global);
goog.exportSymbol('proto.types.SignedTransactionProof', null, global);
goog.exportSymbol('proto.types.SparseMerkleProof', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.AccumulatorProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.types.AccumulatorProof.repeatedFields_, null);
};
goog.inherits(proto.types.AccumulatorProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.AccumulatorProof.displayName = 'proto.types.AccumulatorProof';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.types.AccumulatorProof.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.AccumulatorProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.AccumulatorProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.AccumulatorProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.AccumulatorProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    bitmap: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nonDefaultSiblingsList: msg.getNonDefaultSiblingsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.AccumulatorProof}
 */
proto.types.AccumulatorProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.AccumulatorProof;
  return proto.types.AccumulatorProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.AccumulatorProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.AccumulatorProof}
 */
proto.types.AccumulatorProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBitmap(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addNonDefaultSiblings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.AccumulatorProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.AccumulatorProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.AccumulatorProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.AccumulatorProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBitmap();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getNonDefaultSiblingsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
};


/**
 * optional uint64 bitmap = 1;
 * @return {number}
 */
proto.types.AccumulatorProof.prototype.getBitmap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.types.AccumulatorProof.prototype.setBitmap = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated bytes non_default_siblings = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.types.AccumulatorProof.prototype.getNonDefaultSiblingsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes non_default_siblings = 2;
 * This is a type-conversion wrapper around `getNonDefaultSiblingsList()`
 * @return {!Array<string>}
 */
proto.types.AccumulatorProof.prototype.getNonDefaultSiblingsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getNonDefaultSiblingsList()));
};


/**
 * repeated bytes non_default_siblings = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNonDefaultSiblingsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.types.AccumulatorProof.prototype.getNonDefaultSiblingsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getNonDefaultSiblingsList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.types.AccumulatorProof.prototype.setNonDefaultSiblingsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.types.AccumulatorProof.prototype.addNonDefaultSiblings = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.types.AccumulatorProof.prototype.clearNonDefaultSiblingsList = function() {
  this.setNonDefaultSiblingsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.SparseMerkleProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.types.SparseMerkleProof.repeatedFields_, null);
};
goog.inherits(proto.types.SparseMerkleProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.SparseMerkleProof.displayName = 'proto.types.SparseMerkleProof';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.types.SparseMerkleProof.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.SparseMerkleProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.SparseMerkleProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.SparseMerkleProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.SparseMerkleProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    leaf: msg.getLeaf_asB64(),
    bitmap: msg.getBitmap_asB64(),
    nonDefaultSiblingsList: msg.getNonDefaultSiblingsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.SparseMerkleProof}
 */
proto.types.SparseMerkleProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.SparseMerkleProof;
  return proto.types.SparseMerkleProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.SparseMerkleProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.SparseMerkleProof}
 */
proto.types.SparseMerkleProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setLeaf(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBitmap(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addNonDefaultSiblings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.SparseMerkleProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.SparseMerkleProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.SparseMerkleProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.SparseMerkleProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLeaf_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getBitmap_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getNonDefaultSiblingsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      3,
      f
    );
  }
};


/**
 * optional bytes leaf = 1;
 * @return {!(string|Uint8Array)}
 */
proto.types.SparseMerkleProof.prototype.getLeaf = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes leaf = 1;
 * This is a type-conversion wrapper around `getLeaf()`
 * @return {string}
 */
proto.types.SparseMerkleProof.prototype.getLeaf_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getLeaf()));
};


/**
 * optional bytes leaf = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getLeaf()`
 * @return {!Uint8Array}
 */
proto.types.SparseMerkleProof.prototype.getLeaf_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getLeaf()));
};


/** @param {!(string|Uint8Array)} value */
proto.types.SparseMerkleProof.prototype.setLeaf = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes bitmap = 2;
 * @return {!(string|Uint8Array)}
 */
proto.types.SparseMerkleProof.prototype.getBitmap = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes bitmap = 2;
 * This is a type-conversion wrapper around `getBitmap()`
 * @return {string}
 */
proto.types.SparseMerkleProof.prototype.getBitmap_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBitmap()));
};


/**
 * optional bytes bitmap = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBitmap()`
 * @return {!Uint8Array}
 */
proto.types.SparseMerkleProof.prototype.getBitmap_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBitmap()));
};


/** @param {!(string|Uint8Array)} value */
proto.types.SparseMerkleProof.prototype.setBitmap = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * repeated bytes non_default_siblings = 3;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.types.SparseMerkleProof.prototype.getNonDefaultSiblingsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * repeated bytes non_default_siblings = 3;
 * This is a type-conversion wrapper around `getNonDefaultSiblingsList()`
 * @return {!Array<string>}
 */
proto.types.SparseMerkleProof.prototype.getNonDefaultSiblingsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getNonDefaultSiblingsList()));
};


/**
 * repeated bytes non_default_siblings = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNonDefaultSiblingsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.types.SparseMerkleProof.prototype.getNonDefaultSiblingsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getNonDefaultSiblingsList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.types.SparseMerkleProof.prototype.setNonDefaultSiblingsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.types.SparseMerkleProof.prototype.addNonDefaultSiblings = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.types.SparseMerkleProof.prototype.clearNonDefaultSiblingsList = function() {
  this.setNonDefaultSiblingsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.SignedTransactionProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.types.SignedTransactionProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.SignedTransactionProof.displayName = 'proto.types.SignedTransactionProof';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.SignedTransactionProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.SignedTransactionProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.SignedTransactionProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.SignedTransactionProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerInfoToTransactionInfoProof: (f = msg.getLedgerInfoToTransactionInfoProof()) && proto.types.AccumulatorProof.toObject(includeInstance, f),
    transactionInfo: (f = msg.getTransactionInfo()) && transaction_info_pb.TransactionInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.SignedTransactionProof}
 */
proto.types.SignedTransactionProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.SignedTransactionProof;
  return proto.types.SignedTransactionProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.SignedTransactionProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.SignedTransactionProof}
 */
proto.types.SignedTransactionProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.types.AccumulatorProof;
      reader.readMessage(value,proto.types.AccumulatorProof.deserializeBinaryFromReader);
      msg.setLedgerInfoToTransactionInfoProof(value);
      break;
    case 2:
      var value = new transaction_info_pb.TransactionInfo;
      reader.readMessage(value,transaction_info_pb.TransactionInfo.deserializeBinaryFromReader);
      msg.setTransactionInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.SignedTransactionProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.SignedTransactionProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.SignedTransactionProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.SignedTransactionProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerInfoToTransactionInfoProof();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.types.AccumulatorProof.serializeBinaryToWriter
    );
  }
  f = message.getTransactionInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      transaction_info_pb.TransactionInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccumulatorProof ledger_info_to_transaction_info_proof = 1;
 * @return {?proto.types.AccumulatorProof}
 */
proto.types.SignedTransactionProof.prototype.getLedgerInfoToTransactionInfoProof = function() {
  return /** @type{?proto.types.AccumulatorProof} */ (
    jspb.Message.getWrapperField(this, proto.types.AccumulatorProof, 1));
};


/** @param {?proto.types.AccumulatorProof|undefined} value */
proto.types.SignedTransactionProof.prototype.setLedgerInfoToTransactionInfoProof = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.types.SignedTransactionProof.prototype.clearLedgerInfoToTransactionInfoProof = function() {
  this.setLedgerInfoToTransactionInfoProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.SignedTransactionProof.prototype.hasLedgerInfoToTransactionInfoProof = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionInfo transaction_info = 2;
 * @return {?proto.types.TransactionInfo}
 */
proto.types.SignedTransactionProof.prototype.getTransactionInfo = function() {
  return /** @type{?proto.types.TransactionInfo} */ (
    jspb.Message.getWrapperField(this, transaction_info_pb.TransactionInfo, 2));
};


/** @param {?proto.types.TransactionInfo|undefined} value */
proto.types.SignedTransactionProof.prototype.setTransactionInfo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.types.SignedTransactionProof.prototype.clearTransactionInfo = function() {
  this.setTransactionInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.SignedTransactionProof.prototype.hasTransactionInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.AccountStateProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.types.AccountStateProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.AccountStateProof.displayName = 'proto.types.AccountStateProof';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.AccountStateProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.AccountStateProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.AccountStateProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.AccountStateProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerInfoToTransactionInfoProof: (f = msg.getLedgerInfoToTransactionInfoProof()) && proto.types.AccumulatorProof.toObject(includeInstance, f),
    transactionInfo: (f = msg.getTransactionInfo()) && transaction_info_pb.TransactionInfo.toObject(includeInstance, f),
    transactionInfoToAccountProof: (f = msg.getTransactionInfoToAccountProof()) && proto.types.SparseMerkleProof.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.AccountStateProof}
 */
proto.types.AccountStateProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.AccountStateProof;
  return proto.types.AccountStateProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.AccountStateProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.AccountStateProof}
 */
proto.types.AccountStateProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.types.AccumulatorProof;
      reader.readMessage(value,proto.types.AccumulatorProof.deserializeBinaryFromReader);
      msg.setLedgerInfoToTransactionInfoProof(value);
      break;
    case 2:
      var value = new transaction_info_pb.TransactionInfo;
      reader.readMessage(value,transaction_info_pb.TransactionInfo.deserializeBinaryFromReader);
      msg.setTransactionInfo(value);
      break;
    case 3:
      var value = new proto.types.SparseMerkleProof;
      reader.readMessage(value,proto.types.SparseMerkleProof.deserializeBinaryFromReader);
      msg.setTransactionInfoToAccountProof(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.AccountStateProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.AccountStateProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.AccountStateProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.AccountStateProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerInfoToTransactionInfoProof();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.types.AccumulatorProof.serializeBinaryToWriter
    );
  }
  f = message.getTransactionInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      transaction_info_pb.TransactionInfo.serializeBinaryToWriter
    );
  }
  f = message.getTransactionInfoToAccountProof();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.types.SparseMerkleProof.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccumulatorProof ledger_info_to_transaction_info_proof = 1;
 * @return {?proto.types.AccumulatorProof}
 */
proto.types.AccountStateProof.prototype.getLedgerInfoToTransactionInfoProof = function() {
  return /** @type{?proto.types.AccumulatorProof} */ (
    jspb.Message.getWrapperField(this, proto.types.AccumulatorProof, 1));
};


/** @param {?proto.types.AccumulatorProof|undefined} value */
proto.types.AccountStateProof.prototype.setLedgerInfoToTransactionInfoProof = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.types.AccountStateProof.prototype.clearLedgerInfoToTransactionInfoProof = function() {
  this.setLedgerInfoToTransactionInfoProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.AccountStateProof.prototype.hasLedgerInfoToTransactionInfoProof = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionInfo transaction_info = 2;
 * @return {?proto.types.TransactionInfo}
 */
proto.types.AccountStateProof.prototype.getTransactionInfo = function() {
  return /** @type{?proto.types.TransactionInfo} */ (
    jspb.Message.getWrapperField(this, transaction_info_pb.TransactionInfo, 2));
};


/** @param {?proto.types.TransactionInfo|undefined} value */
proto.types.AccountStateProof.prototype.setTransactionInfo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.types.AccountStateProof.prototype.clearTransactionInfo = function() {
  this.setTransactionInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.AccountStateProof.prototype.hasTransactionInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SparseMerkleProof transaction_info_to_account_proof = 3;
 * @return {?proto.types.SparseMerkleProof}
 */
proto.types.AccountStateProof.prototype.getTransactionInfoToAccountProof = function() {
  return /** @type{?proto.types.SparseMerkleProof} */ (
    jspb.Message.getWrapperField(this, proto.types.SparseMerkleProof, 3));
};


/** @param {?proto.types.SparseMerkleProof|undefined} value */
proto.types.AccountStateProof.prototype.setTransactionInfoToAccountProof = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.types.AccountStateProof.prototype.clearTransactionInfoToAccountProof = function() {
  this.setTransactionInfoToAccountProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.AccountStateProof.prototype.hasTransactionInfoToAccountProof = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.EventProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.types.EventProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.EventProof.displayName = 'proto.types.EventProof';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.EventProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.EventProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.EventProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.EventProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerInfoToTransactionInfoProof: (f = msg.getLedgerInfoToTransactionInfoProof()) && proto.types.AccumulatorProof.toObject(includeInstance, f),
    transactionInfo: (f = msg.getTransactionInfo()) && transaction_info_pb.TransactionInfo.toObject(includeInstance, f),
    transactionInfoToEventProof: (f = msg.getTransactionInfoToEventProof()) && proto.types.AccumulatorProof.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.EventProof}
 */
proto.types.EventProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.EventProof;
  return proto.types.EventProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.EventProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.EventProof}
 */
proto.types.EventProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.types.AccumulatorProof;
      reader.readMessage(value,proto.types.AccumulatorProof.deserializeBinaryFromReader);
      msg.setLedgerInfoToTransactionInfoProof(value);
      break;
    case 2:
      var value = new transaction_info_pb.TransactionInfo;
      reader.readMessage(value,transaction_info_pb.TransactionInfo.deserializeBinaryFromReader);
      msg.setTransactionInfo(value);
      break;
    case 3:
      var value = new proto.types.AccumulatorProof;
      reader.readMessage(value,proto.types.AccumulatorProof.deserializeBinaryFromReader);
      msg.setTransactionInfoToEventProof(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.EventProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.EventProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.EventProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.EventProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerInfoToTransactionInfoProof();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.types.AccumulatorProof.serializeBinaryToWriter
    );
  }
  f = message.getTransactionInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      transaction_info_pb.TransactionInfo.serializeBinaryToWriter
    );
  }
  f = message.getTransactionInfoToEventProof();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.types.AccumulatorProof.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccumulatorProof ledger_info_to_transaction_info_proof = 1;
 * @return {?proto.types.AccumulatorProof}
 */
proto.types.EventProof.prototype.getLedgerInfoToTransactionInfoProof = function() {
  return /** @type{?proto.types.AccumulatorProof} */ (
    jspb.Message.getWrapperField(this, proto.types.AccumulatorProof, 1));
};


/** @param {?proto.types.AccumulatorProof|undefined} value */
proto.types.EventProof.prototype.setLedgerInfoToTransactionInfoProof = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.types.EventProof.prototype.clearLedgerInfoToTransactionInfoProof = function() {
  this.setLedgerInfoToTransactionInfoProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.EventProof.prototype.hasLedgerInfoToTransactionInfoProof = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionInfo transaction_info = 2;
 * @return {?proto.types.TransactionInfo}
 */
proto.types.EventProof.prototype.getTransactionInfo = function() {
  return /** @type{?proto.types.TransactionInfo} */ (
    jspb.Message.getWrapperField(this, transaction_info_pb.TransactionInfo, 2));
};


/** @param {?proto.types.TransactionInfo|undefined} value */
proto.types.EventProof.prototype.setTransactionInfo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.types.EventProof.prototype.clearTransactionInfo = function() {
  this.setTransactionInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.EventProof.prototype.hasTransactionInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AccumulatorProof transaction_info_to_event_proof = 3;
 * @return {?proto.types.AccumulatorProof}
 */
proto.types.EventProof.prototype.getTransactionInfoToEventProof = function() {
  return /** @type{?proto.types.AccumulatorProof} */ (
    jspb.Message.getWrapperField(this, proto.types.AccumulatorProof, 3));
};


/** @param {?proto.types.AccumulatorProof|undefined} value */
proto.types.EventProof.prototype.setTransactionInfoToEventProof = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.types.EventProof.prototype.clearTransactionInfoToEventProof = function() {
  this.setTransactionInfoToEventProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.EventProof.prototype.hasTransactionInfoToEventProof = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.types);
