/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var events_pb = require('./events_pb.js');
goog.object.extend(proto, events_pb);
var ledger_info_pb = require('./ledger_info_pb.js');
goog.object.extend(proto, ledger_info_pb);
goog.exportSymbol('proto.types.ValidatorChangeEventWithProof', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.ValidatorChangeEventWithProof = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.types.ValidatorChangeEventWithProof, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.ValidatorChangeEventWithProof.displayName = 'proto.types.ValidatorChangeEventWithProof';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.ValidatorChangeEventWithProof.prototype.toObject = function(opt_includeInstance) {
  return proto.types.ValidatorChangeEventWithProof.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.ValidatorChangeEventWithProof} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ValidatorChangeEventWithProof.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerInfoWithSigs: (f = msg.getLedgerInfoWithSigs()) && ledger_info_pb.LedgerInfoWithSignatures.toObject(includeInstance, f),
    eventWithProof: (f = msg.getEventWithProof()) && events_pb.EventWithProof.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.ValidatorChangeEventWithProof}
 */
proto.types.ValidatorChangeEventWithProof.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.ValidatorChangeEventWithProof;
  return proto.types.ValidatorChangeEventWithProof.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.ValidatorChangeEventWithProof} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.ValidatorChangeEventWithProof}
 */
proto.types.ValidatorChangeEventWithProof.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ledger_info_pb.LedgerInfoWithSignatures;
      reader.readMessage(value,ledger_info_pb.LedgerInfoWithSignatures.deserializeBinaryFromReader);
      msg.setLedgerInfoWithSigs(value);
      break;
    case 2:
      var value = new events_pb.EventWithProof;
      reader.readMessage(value,events_pb.EventWithProof.deserializeBinaryFromReader);
      msg.setEventWithProof(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.ValidatorChangeEventWithProof.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.ValidatorChangeEventWithProof.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.ValidatorChangeEventWithProof} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ValidatorChangeEventWithProof.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerInfoWithSigs();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ledger_info_pb.LedgerInfoWithSignatures.serializeBinaryToWriter
    );
  }
  f = message.getEventWithProof();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      events_pb.EventWithProof.serializeBinaryToWriter
    );
  }
};


/**
 * optional LedgerInfoWithSignatures ledger_info_with_sigs = 1;
 * @return {?proto.types.LedgerInfoWithSignatures}
 */
proto.types.ValidatorChangeEventWithProof.prototype.getLedgerInfoWithSigs = function() {
  return /** @type{?proto.types.LedgerInfoWithSignatures} */ (
    jspb.Message.getWrapperField(this, ledger_info_pb.LedgerInfoWithSignatures, 1));
};


/** @param {?proto.types.LedgerInfoWithSignatures|undefined} value */
proto.types.ValidatorChangeEventWithProof.prototype.setLedgerInfoWithSigs = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.types.ValidatorChangeEventWithProof.prototype.clearLedgerInfoWithSigs = function() {
  this.setLedgerInfoWithSigs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.ValidatorChangeEventWithProof.prototype.hasLedgerInfoWithSigs = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EventWithProof event_with_proof = 2;
 * @return {?proto.types.EventWithProof}
 */
proto.types.ValidatorChangeEventWithProof.prototype.getEventWithProof = function() {
  return /** @type{?proto.types.EventWithProof} */ (
    jspb.Message.getWrapperField(this, events_pb.EventWithProof, 2));
};


/** @param {?proto.types.EventWithProof|undefined} value */
proto.types.ValidatorChangeEventWithProof.prototype.setEventWithProof = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.types.ValidatorChangeEventWithProof.prototype.clearEventWithProof = function() {
  this.setEventWithProof(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.types.ValidatorChangeEventWithProof.prototype.hasEventWithProof = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.types);
