/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var validator_public_keys_pb = require('./validator_public_keys_pb.js');
goog.object.extend(proto, validator_public_keys_pb);
goog.exportSymbol('proto.types.ValidatorSet', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.ValidatorSet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.types.ValidatorSet.repeatedFields_, null);
};
goog.inherits(proto.types.ValidatorSet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.ValidatorSet.displayName = 'proto.types.ValidatorSet';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.types.ValidatorSet.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.ValidatorSet.prototype.toObject = function(opt_includeInstance) {
  return proto.types.ValidatorSet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.ValidatorSet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ValidatorSet.toObject = function(includeInstance, msg) {
  var f, obj = {
    validatorPublicKeysList: jspb.Message.toObjectList(msg.getValidatorPublicKeysList(),
    validator_public_keys_pb.ValidatorPublicKeys.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.ValidatorSet}
 */
proto.types.ValidatorSet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.ValidatorSet;
  return proto.types.ValidatorSet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.ValidatorSet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.ValidatorSet}
 */
proto.types.ValidatorSet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new validator_public_keys_pb.ValidatorPublicKeys;
      reader.readMessage(value,validator_public_keys_pb.ValidatorPublicKeys.deserializeBinaryFromReader);
      msg.addValidatorPublicKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.ValidatorSet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.ValidatorSet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.ValidatorSet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ValidatorSet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidatorPublicKeysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      validator_public_keys_pb.ValidatorPublicKeys.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ValidatorPublicKeys validator_public_keys = 1;
 * @return {!Array<!proto.types.ValidatorPublicKeys>}
 */
proto.types.ValidatorSet.prototype.getValidatorPublicKeysList = function() {
  return /** @type{!Array<!proto.types.ValidatorPublicKeys>} */ (
    jspb.Message.getRepeatedWrapperField(this, validator_public_keys_pb.ValidatorPublicKeys, 1));
};


/** @param {!Array<!proto.types.ValidatorPublicKeys>} value */
proto.types.ValidatorSet.prototype.setValidatorPublicKeysList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.types.ValidatorPublicKeys=} opt_value
 * @param {number=} opt_index
 * @return {!proto.types.ValidatorPublicKeys}
 */
proto.types.ValidatorSet.prototype.addValidatorPublicKeys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.types.ValidatorPublicKeys, opt_index);
};


proto.types.ValidatorSet.prototype.clearValidatorPublicKeysList = function() {
  this.setValidatorPublicKeysList([]);
};


goog.object.extend(exports, proto.types);
